#!/bin/bash

# Integration with ripgrep, stolen from fzf documentation
RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case -g '*.$1'"
INITIAL_QUERY=""
FZF_DEFAULT_COMMAND="$RG_PREFIX '$INITIAL_QUERY'" \
fzf --bind "change:reload:$RG_PREFIX {q} || true" \
--delimiter : \
--ansi --disabled --query "$INITIAL_QUERY"  \
--preview "bat --color always -H{2} {1} " \
--preview-window "+{2}-10" \
--bind "enter:execute(nvim +{2} {1})"
